# 스터디 관련 API를 테스트하는 HTTP 요청 파일입니다.

# 공통 파라미터 설정
@base_local = http://localhost:3000/api
@base_prod = https://eight-studyforest-team2-be.onrender.com/api
@studyId = 1
@pwd = 1234
# 조회 API를 위한 파라미터 설정
@limit = 100
@offset = 0
@order = points_asc
@isActive = true
@keyword =

### 1) [로컬] 스터디 관리 페이지 조회 (관리자용)

GET {{base_local}}/studies/manage

### 2) [배포] 스터디 조회 API (offset, pointOrder, recentOrder, isActive, keyword)

GET {{base_prod}}/studies?limit={{limit}}&offset={{offset}}&sort={{order}}&isActive={{isActive}}&keyword={{keyword}}

### 2) [로컬] 스터디 조회 API (offset, pointOrder, recentOrder, isActive, keyword)

GET {{base_local}}/studies?limit={{limit}}&offset={{offset}}&sort={{order}}&isActive={{isActive}}&keyword={{keyword}}

### 3) [배포] 스터디 생성 API

POST {{base_prod}}/studies
Content-Type: application/json

{
    "nick": "테스트",
    "name": "스터디 생성 테스트",
    "content": "스터디 생성 테스트 중 입니다.",
    "img": "https://avatars.githubusercontent.com/in/347564?s=60&v=4",
    "password": "{{pwd}}",
    "checkPassword": "{{pwd}}",
    "isActive": true
}

### 3) [로컬] 스터디 생성 API

POST {{base_local}}/studies
Content-Type: application/json

{
    "nick": "테스트",
    "name": "스터디 생성 테스트",
    "content": "스터디 생성 테스트 중 입니다.",
    "img": "https://avatars.githubusercontent.com/in/347564?s=60&v=4",
    "password": "{{pwd}}",
    "checkPassword": "{{pwd}}",
    "isActive": true
}

### 4) [배포] 스터디 수정 API

PATCH {{base_prod}}/studies/{{studyId}}
Content-Type: application/json

{
    "nick": "테스트",
    "name": "스터디 수정 테스트",
    "content": "스터디 수정 테스트 중 입니다.",
    "img": "https://avatars.githubusercontent.com/in/347564?s=60&v=4",
    "password": "{{pwd}}",
    "isActive": true
}

### 4) [로컬] 스터디 수정 API

PATCH {{base_local}}/studies/{{studyId}}
Content-Type: application/json

{
    "nick": "테스트",
    "name": "스터디 수정 테스트",
    "content": "스터디 수정 테스트 중 입니다.",
    "img": "https://avatars.githubusercontent.com/in/347564?s=60&v=4",
    "password": "{{pwd}}",
    "isActive": true
}

### 5) [배포] 스터디 삭제 API

DELETE {{base_prod}}/studies/{{studyId}}
Content-Type: application/json

{
  "password": "{{pwd}}"
}

### 5) [로컬] 스터디 삭제 API

DELETE {{base_local}}/studies/{{studyId}}
Content-Type: application/json

{
  "password": "{{pwd}}"
}

### 6) [배포] 스터디 단일 조회 API

GET {{base_prod}}/studies/{{studyId}}

### 6) [로컬] 스터디 단일 조회 API

GET {{base_local}}/studies/{{studyId}}

### 7) [로컬] 스터디 비밀번호 검증 API

POST {{base_local}}/studies/{{studyId}}/verify-password
Content-Type: application/json

{
  "password": "{{pwd}}"
}

### 7) [배포] 스터디 비밀번호 검증 API
POST {{base_prod}}/studies/{{studyId}}/verify-password
Content-Type: application/json

{
  "password": "{{pwd}}"
}

### 7) [로컬] 이모지 횟수 증가 API

POST {{base_local}}/studies/{{studyId}}/emojis/increment
Content-Type: application/json

{
    "id": "1f603",
    "emoji": "😃",
    "count": 1
}

### 7) [배포] 이모지 횟수 증가 API

POST {{base_prod}}/studies/{{studyId}}/emojis/increment
Content-Type: application/json

{
    "id": "1f603",
    "emoji": "😃",
    "count": 1
}

### 8) [로컬] 이모지 횟수 감소 API

POST {{base_local}}/studies/{{studyId}}/emojis/decrement
Content-Type: application/json

{
    "id": "1f603",
    "emoji": "😃",
    "count": 1
}